### PR TITLE
Python3 support

### PR DESCRIPTION
**Pull request by xyder**
I continued the work @jeryini started and I finished the python 3 support implementation.
Changes:
- fixed some pre-existing bugs in the salesforce_bulkipy module and ensured all methods work
- added more tests to cover more of the functionality
- updated the existing tests to take into consideration changes that were made to the salesforce_bulkipy module
- added more assertions in some tests to make them more strict

Please review the code and I will squash the commits after the changes are approved.

### CODE REVIEW

**Comment by bholagabbar** [comment]
@xyder These look good. Can you squash the commits? Have you tested these on a Sandbox/Salesforce Instance?

**Comment by xyder** [comment]
@bholagabbar I squashed the commits and also updated the readme file.
Yes, I ran all the tests and did some manual testing too on a Sandbox Salesforce instance, both for py2 and py3.

**Comment by ndanielsen** [comment]
@xyder, in setup.py there is python2 print statement and e.message error on LOC 30 that triggers an error when you run `setup.py install`

**Comment by ndanielsen** [comment]
@bholagabbar I tested this out locally and it works great, the sooner to merge in the better!

**Comment by bholagabbar** [comment]
@ndanielsen @xyder Merged!

**Comment by jeryini** [comment]
@bholagabbar, could you please create a new release and also release it on [pypi](https://pypi.python.org/pypi/salesforce-bulkipy/1.0)? Thank you!

**Pull request merged**
